### ISSUE TITLE
Realtime form preview update on changes

### ISSUE THREAD

**Issue by ChaudharyPradip** [piyushgarg-dev/review-app#101]
### Is your proposal related to a problem?

When we change our form the preview on the right-hand side doesn't change. We need to save the form in order to see the changes which costs us database mutation every time the user wants a preview of the changes which is not ideal.

https://github.com/piyushgarg-dev/review-app/assets/88336529/55bb2358-cd53-4e00-99a3-029e471ce2d4

### Describe the solution you'd like

The UI(form preview) on the right side should update when the form is changed. This will give users immediate feedback and will save us API calls for users to see the changes.

**Comment by ChaudharyPradip** [comment]
Hey @hemantwasthere ,
I have already solved this issue and would love to submit a pull request if you agree to this.

**Comment by piyushgarg-dev** [comment]
Hey @ChaudharyPradip 
Assigned
