### ISSUE TITLE
[Bug]: Checkbox Bug - Selecting All Forms on Dashboard

### ISSUE THREAD

**Issue by yahyaa19** [piyushgarg-dev/review-app#120]
### Describe the bug

When using the form review app, I encountered a bug on the dashboard where multiple forms are listed. In this scenario, there are **checkboxes** in front of each form to select them individually for actions like deletion or marking as reviewed. However, the issue arises when I attempt to select a single form by clicking its checkbox; instead of selecting only the intended form, all checkboxes get selected simultaneously. This unintended behaviour makes it difficult to manage and interact with forms efficiently.

### To Reproduce

1. Go to 'http://app.localhost:3000/dashboard/'
2. Click on 'Forms in the Collect Section'
3. Observe the checkboxes in front of each form.
4. Attempt to select a single form by clicking its checkbox.
5. See error

### Expected behavior

Clicking on the checkbox of an individual form should select only that **specific form**.

### Screenshots/Videos

![image](https://github.com/piyushgarg-dev/review-app/assets/95754053/b343602e-cc3f-495f-9078-bd57d779fa22)

https://github.com/piyushgarg-dev/review-app/assets/95754053/24d85548-13aa-424b-8507-93f25342039d

### Additional context

Browser/Device: Brave/ Asus G14
Operating System: Windows 11

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by Mosam219** [comment]
Hii, I have solved selection of individual form. should I add more functionality because i can't see any actions after selecting forms.

**Comment by yahyaa19** [comment]
> Hii, I have solved selection of individual form. should I add more functionality because i can't see any actions after selecting forms. Let me know if we need any more changes

Hey its working perfectly now thank you for fixing this bug.

**Comment by piyushgarg-dev** [comment]
Closing in Ref PR https://github.com/piyushgarg-dev/review-app/pull/121
