### ISSUE TITLE
Password Visiblity Feature For Better Ux

### ISSUE THREAD

**Issue by Kiranism** [piyushgarg-dev/review-app#127]
### Is your proposal related to a problem?
NO, its a feature request.

Password Visiblity Feature For Better Ux, struggling to find what characters entered in the password field.

### Describe the solution you'd like
Better to add a toggle eye icon to visible user entered characters in the password field.

  ![image](https://github.com/piyushgarg-dev/review-app/assets/68379183/ebc12e92-a327-4de3-80ad-bf649594455d)

**Comment by aarjun8060** [comment]
I want working on this issue. Can you please tell me which form we want this eye visibility 
--------- this form is SignIn and Login Page 
<img width="399" alt="Screenshot 2023-10-12 084231" src="https://github.com/piyushgarg-dev/review-app/assets/117923579/7b82351c-cf7f-43ce-84ba-1c6811ed8487">
<img width="419" alt="Screenshot 2023-10-12 084211" src="https://github.com/piyushgarg-dev/review-app/assets/117923579/9c7085cd-56ad-4920-a166-8c7a7704bbe5">

**Comment by Sarhan41** [comment]
@aarjun8060 how you had add that eye icon and visibility functionality in the server side page, can you please share it ?

**Comment by Kiranism** [comment]
#133 Added Custom Password Input with Show and Hide Feature for Sign-In and Sign-Up Pages
