### ISSUE TITLE
Warning: Uncontrolled to Controlled Input Transition at signup page

### ISSUE THREAD

**Issue by C0dewithLokesh** [piyushgarg-dev/review-app#13]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I encountered a warning message in my React application with the following details:
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen.

### Steps to Reproduce

1. Visit the signup page by navigating to http://app.localhost:3000/signup.
2. On the signup page, locate the "Last Name" input field.
3. Make any changes or edits in the "Last Name" input field.

### Actual Results

- A warning message appears in the console during component rendering, indicating a transition from an uncontrolled input to a controlled input due to a value change.

### Expected Results

- I expected the application to handle input elements consistently, either as controlled or uncontrolled inputs, without triggering warnings of this nature.

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

![image](https://github.com/piyushgarg-dev/review-app/assets/77185999/28b13223-fbb2-428a-a41b-76888c912dd6)

**Comment by Codensity30** [comment]
can I start working on it?

**Comment by C0dewithLokesh** [comment]
i'm already creating a pull request for this issure

**Comment by Codensity30** [comment]
no problem, will be looking for other
