### ISSUE TITLE
Update Form Edit Page Dark theme color 

### ISSUE THREAD

**Issue by saadabban76** [piyushgarg-dev/review-app#130]
### Is your proposal related to a problem?
No.

I
![image](https://github.com/piyushgarg-dev/review-app/assets/115649011/e30fa9f3-41d7-4050-a56d-a89fd74ed4e7)
the dark gray background doesn't give dark theme vibes its hurting eyes. I would like to change the color of the background !

### Describe the solution you'd like
the blackish grey would look good something like this : 
![image](https://github.com/piyushgarg-dev/review-app/assets/115649011/9a09830c-a87d-4221-a6ed-657eab4f6f8f)

**Comment by aarjun8060** [comment]
working

**Comment by saadabban76** [comment]
Already worked on it @aarjun8060 just waiting for @piyushgarg-dev to assign the issue to me!

**Comment by aarjun8060** [comment]
@saadabban76  good bro! I want to try to solve this. Can I  working on this .
