### ISSUE TITLE
Implementation of State Management Library in App.

### ISSUE THREAD

**Issue by saadabban76** [piyushgarg-dev/review-app#131]
### Is your proposal related to a problem?

The Frontend has not yet implemented state management !

### Describe the solution you'd like

We can use recoil/redux as the State Management Libraries.
in my opinion recoil would be a good option to go with since it is easy write and comes up with less boiler code .

**Comment by saadabban76** [comment]
I would like to work on this issue please assign this to me @piyushgarg-dev

**Comment by saadabban76** [comment]
@piyushgarg-dev which library do you suggest redux or recoil ?

**Comment by Your-Ehsan** [comment]
I think we should work with zustand in this project because its beginner friendly and easy to use.

**Comment by saadabban76** [comment]
> I think we should work with zustand in this project because its beginner friendly and easy to use.

yup anything is fine ! lets wait for piyush reply

**Comment by Your-Ehsan** [comment]
@piyushgarg-dev  what's your opinion about this ?

**Comment by Your-Ehsan** [comment]
@saadabban76 I checked the code now the zustand package is already installed in this. So, I think we should close this issue now.

**Comment by saadabban76** [comment]
@Your-Ehsan yeh i just saw zustand is already in !
