### ISSUE TITLE
[Bug]: Can't be able to access more actions with a single click.

### ISSUE THREAD

**Issue by suhasjadhav264** [piyushgarg-dev/review-app#132]
### Describe the bug

When we are in the review form, there is an action button (a pencil icon). If we try to click it, we won't be able to access more actions with a single click. We have to double-click it.

### To Reproduce

1. Go to http://app.localhost:3000/signin
2. Click on forms
3. Open any review form that you have created.
4. Click on action button (pencil icon)
5. See bug

### Expected behavior

The action button (pencil icon) should allow users to access more actions with only one click.

### Screenshots/Videos

https://github.com/piyushgarg-dev/review-app/assets/97833559/785b31fb-da23-4f76-b5b0-32f94746734c

![Screenshot (876)](https://github.com/piyushgarg-dev/review-app/assets/97833559/f922a7d5-26e7-4b23-aef3-d1cbe6eb5050)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by Anandateertha** [comment]
Can you just brief about what type of actions you need when you click on the action button?

**Comment by suhasjadhav264** [comment]
> Can you just brief about what type of actions you need when you click on the action button?

@Anandateertha  As I showed in the screenshot, there are more actions and a hide menu. When you click that icon, you will get to know.

**Comment by iceTmZz** [comment]
> > Can you just brief about what type of actions you need when you click on the action button?
> 
> @Anandateertha As I showed in the screenshot, there are more actions and a hide menu. When you click that icon, you will get to know.

I don't think it's an issue, cause it is just an img not a button

**Comment by suhasjadhav264** [comment]
> > > Can you just brief about what type of actions you need when you click on the action button?
> > 
> > 
> > @Anandateertha As I showed in the screenshot, there are more actions and a hide menu. When you click that icon, you will get to know.
> 
> I don't think it's an issue, cause it is just an img not a button

yeah! What is the use of it? We should add a form rename action button.

**Comment by Anandateertha** [comment]
I have added the functionality to the pencil icon such that when user clicks it form name can be edited. 
PR: #148
