### ISSUE TITLE
[Bug]: Forgot Password Page is not created 

### ISSUE THREAD

**Issue by Atharva1723** [piyushgarg-dev/review-app#140]
### Describe the bug

I encountered a problem when using the web application's sign-in page. When I click on the "Forgot Password" button, I'm redirected to the signup page instead of a "Forgot Password" page. This behavior is not as expected.

### To Reproduce

1. Go to the web application's sign-in page.
2. Click on the "Forgot Password" button.
3. It redirects to the signup page 

### Expected behavior

I expected to be redirected to a "Forgot Password" page where I could reset my password. I have checked in the repository pages folder, and the forgot password page has not been created.

### Screenshots/Videos

![image](https://github.com/piyushgarg-dev/review-app/assets/87201444/69018f9e-0478-4b83-8059-0692c259861d)

### Additional context

Browser: Chrome 
Operating System: Windows 10

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by shakthi2003-ice** [comment]
Can you assign me this issue?

**Comment by Atharva1723** [comment]
@shakthi2003-ice  Please can I take this issue? Maybe you could take some other issue like #132 or #116

**Comment by hemantwasthere** [comment]
Closing reason in #141 comments
