### ISSUE TITLE
[Bug]: When user clicks on the form link, no action is performed.

### ISSUE THREAD

**Issue by Anandateertha** [piyushgarg-dev/review-app#149]
### Describe the bug

When the user clicks on the form link when a form is created, doesn't perform any action. Refer to the screenshot and videos section below to see the bug visually.

### To Reproduce

1. Go to http://app.localhost:3000/dashboard/subdomain/forms
2. Click on form link
3. See the bug, that clicking on the link doesn't do anything.

### Expected behavior

The expected behavior is that upon clicking the form link the link should be opened in a new tab to view the form by the user.

### Screenshots/Videos

https://github.com/piyushgarg-dev/review-app/assets/131521505/7be12738-5030-430a-b596-846c09c3014b

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by avdhendra** [comment]
can you tell which route it need to direct when clicked

**Comment by Anandateertha** [comment]
> can you tell which route it need to direct when clicked

It will be redirected to form link and user will be able to see the form.

**Comment by hemantwasthere** [comment]
We've already added the redirection to the public form on the click of the form link. Please sync with the latest changes to see it on your computer.
