### ISSUE TITLE
Dark mode and text area bug

### ISSUE THREAD

**Issue by NamelesssNerd** [piyushgarg-dev/review-app#15]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

some of the text color doesn't change according to the mode of webpage [dark/light] in form page and user can resize the size of text area which disturb the Ui. 

### Steps to Reproduce

1. went to form that I have created.
2. when I clicked the form that I have created and navigate to all the accordions I found there is some problem with text and background which color doesn't change according to the mode of the page
3. text area also resizable that might hamper the Ui of webpage when user try to resize [actually when user try to increase the size]

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- al the Ui is fine even in dark mode also

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details
![Screenshot 2023-10-07 182830](https://github.com/piyushgarg-dev/review-app/assets/87481819/6912c8bd-2c6b-4ba4-b21b-d281d940a729)
![Screenshot 2023-10-07 182847](https://github.com/piyushgarg-dev/review-app/assets/87481819/713d399f-ea1d-4938-a182-af753d10c9bf)
![Screenshot 2023-10-07 183216](https://github.com/piyushgarg-dev/review-app/assets/87481819/c097d831-65d5-4dee-a4ff-56f3214af7b2)
![Screenshot 2023-10-07 183704](https://github.com/piyushgarg-dev/review-app/assets/87481819/a09ee936-a078-435c-a948-c51ee92ab4c4)

- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.
![Screenshot 2023-10-07 184128](https://github.com/piyushgarg-dev/review-app/assets/87481819/57ece869-46a3-46f9-a6aa-19391adf8775)
![Screenshot 2023-10-07 184138](https://github.com/piyushgarg-dev/review-app/assets/87481819/c403c843-e079-4ba7-b47c-8228a5def981)

**Comment by JOGINDER571** [comment]
Please assign me

**Comment by Sidopolis** [comment]
Hi Sir! Can i get assigned to this task

**Comment by sushilmagare10** [comment]
**@piyushgarg-dev**  Can I work on this issue...

**Comment by JatinSainiOO7** [comment]
Can I work on this issue.
Thank you.
