### ISSUE TITLE
[feat] : Implement User Authentication System

### ISSUE THREAD

**Issue by Parvezkhan0** [piyushgarg-dev/review-app#174]
### Is your proposal related to a problem?

The current application lacks a user authentication system, which means users can interact with the app without any form of login. This poses a security risk and prevents the personalization of user experience.

### Describe the solution you'd like

I propose implementing a user authentication system. This would involve choosing an authentication method (e.g., email/password), setting up the necessary libraries or packages, creating UI elements for user registration and login, implementing backend logic for authentication and session management, adding error handling and input validation, and thoroughly testing the authentication flow.

### Describe alternatives you've considered

One alternative considered was to continue without user authentication, but this would leave the application vulnerable to unauthorized access and hinder the ability to provide personalized features to users.

### Additional context

This feature is essential for ensuring the security and personalization of the application. It will also pave the way for future enhancements such as user-specific settings and preferences. No related issues have been identified at this time.

**Comment by Parthasarathip123** [comment]
can you assign me this work @Parvezkhan0

**Comment by piyushgarg-dev** [comment]
We already have an authentication setup. Is there something else that you want to set up here 😄?

**Comment by hemantwasthere** [comment]
I think we can close this issue as we already have an authentication setup 😄
