### ISSUE TITLE
[Feat]: Bullet points Feature for form intro message

### ISSUE THREAD

**Issue by amanlajpal** [piyushgarg-dev/review-app#175]
### Is your proposal related to a problem?
Yes

Two Problems
1. When I was editing the form there were two bullet points always visible even though I had not entered any bullet points in the intro message. Therefore, I removed those two bullet points from the intro message input field of the form.
2. When I needed to explicitly add bullet points in the intro message of my form, I was unable to achieve it with the current functionality provided.

![image](https://github.com/piyushgarg-dev/review-app/assets/42869088/96b831fb-4a46-4e90-a1b8-7626b980e191)

### Describe the solution you'd like

 The solution that I would like is, to use hyphens in replacement for bullet points while editing the form's intro message but in the preview, those hyphens must be converted to bullet points smartly 💡.

### Describe alternatives you've considered

Maybe a Markup language engine attached to the input field of the intro message like markdown.

**Comment by avdhendra** [comment]
is this issue already resolve

**Comment by amanlajpal** [comment]
I'm closing this issue, as this is already resolved
