### ISSUE TITLE
Add Reference to Backend Repository in CONTRIBUTING.md

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/review-app#18]
I would prefer if we could add a reference to the review-app-api repository reference to the https://github.com/piyushgarg-dev/review-app/blob/main/CONTRIBUTING.md file so that it's easier for contributors to get started.

Link to Backend Repo: https://github.com/piyushgarg-dev/review-app-api

**Comment by rudransh61** [comment]
i can do it may i

**Comment by kaustab28** [comment]
I can add it? Could you assign it to me under hacktoberfest?

**Comment by rudransh61** [comment]
https://github.com/piyushgarg-dev/review-app/pull/19

**Comment by ShaikhAman01** [comment]
May I do this please @piyushgarg-dev

**Comment by shivamk23** [comment]
done @piyushgarg-dev
