### ISSUE TITLE
[Bug]: Login and Signup page error message and label doesn't look good in dark mode.

### ISSUE THREAD

**Issue by Niranjan-Baur** [piyushgarg-dev/review-app#188]
### Describe the bug

1. The Login and Signup page **error message** doesn't look good, it is tough to see in dark mode.
2. The form labels, turned into red color, which doesn't look good.

### To Reproduce

1. Go to http://app.localhost:3000/signup or http://app.localhost:3000/signin
2. Click on the Sign-Up or Login button without filling in the details
3. Then you can see the error message.

### Expected behavior

1. The error message should be visible in red color.
2. The labels should be in white color. 

![Screenshot (125)](https://github.com/piyushgarg-dev/review-app/assets/73574249/eadd7831-4cbe-4819-994b-86d99aabc3ca)

### Screenshots/Videos

As you can see error message is very hard to see.

![Screenshot (124)](https://github.com/piyushgarg-dev/review-app/assets/73574249/76e98865-0e64-48f2-8cc2-b909d494459a)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by hemantwasthere** [comment]
Closing reason in #189 comments
