### ISSUE TITLE
feature proposal - Greet the contributors

### ISSUE THREAD

**Issue by Junaid-Mohamed** [piyushgarg-dev/review-app#201]
## Is your proposal related to a problem?

No, my proposal is not related to a problem

## Describe the solution you'd like

I would like to propose a feature of greeting the contributors when they ***open an Issue or PR using Github actions and workflows*** and add a personalized comment for the contributors

## Describe alternatives you've considered

Straight forward solution of implementing a github action that would have a workflow

##Additional context

A sample picture of the feature proposed is as follows.

<img width="676" alt="github-action-bot-comment" src="https://github.com/piyushgarg-dev/review-app/assets/64761352/8b5f5a55-9167-4d2c-8fee-ccf146229ee9">

### Requirement/Document
No Documents yet.

**Comment by hemantwasthere** [comment]
Yeah, its great to have a greet message bot.
Assigning this issue to @Junaid-Mohamed and let me know if you're working on this or not.
And also add a bot for a message when PR is merged

**Comment by Junaid-Mohamed** [comment]
@hemantwasthere , I'll work on it
