### ISSUE TITLE
[Feat]: Form delete feature

### ISSUE THREAD

**Issue by amanlajpal** [piyushgarg-dev/review-app#205]
### Is your proposal related to a problem?
No

### Feature Description

Show a popup to confirm the deletion of the form and on confirmation, delete the form!

![image](https://github.com/piyushgarg-dev/review-app/assets/42869088/26c87bd5-84bc-435c-85f5-f633d1c58c40)

**Comment by Naveenchand06** [comment]
Hi👋, I would like to work on this issue

**Comment by yashnirmal** [comment]
Hey would love to work on this one

**Comment by hemantwasthere** [comment]
I'll be taking over this issue!
