### ISSUE TITLE
[Bug]: Favicon and Metadata Missing

### ISSUE THREAD

**Issue by sohan9819** [piyushgarg-dev/review-app#206]
### Describe the bug

The favicon is still the default template icon and Metadata of the app is not available . 

### To Reproduce

1. Go to any route (for example landing page , about page or dashboard  ) 
2. Check the title and favicon of the page

### Expected behavior

Expected Output : 

![image](https://github.com/piyushgarg-dev/review-app/assets/64985447/b8abbd0c-b3b7-41e8-92f4-6014f8f125f7)
![image](https://github.com/piyushgarg-dev/review-app/assets/64985447/b6274634-96fb-4073-ac70-9d7d69ba0adf)

### Screenshots/Videos

Currently favicon and title of the page looks like this

![image](https://github.com/piyushgarg-dev/review-app/assets/64985447/82a75bfa-d2cf-483a-a1fc-ef7888420ffe)
![image](https://github.com/piyushgarg-dev/review-app/assets/64985447/8f9b2c64-b470-43eb-bd27-9156028e4d07)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by Pushpajit** [comment]
I can work on that, assign me

**Comment by sohan9819** [comment]
I have made an pr for this issue
