### ISSUE TITLE
feat: Redirection according to user status on app.localhost:3000

### ISSUE THREAD

**Issue by ChaudharyPradip** [piyushgarg-dev/review-app#208]
### Is your proposal related to a problem?

when a user visits app.localhsot:300 it shows 404 page does not exist

https://github.com/piyushgarg-dev/review-app/assets/88336529/9c7b8b28-cad8-4f73-800b-cd1032919225

(Write your answer here.)

### Describe the solution you'd like

I would like user to be redirected to either signing page or dashboard based on whether they are logged in or not.
(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

**Comment by hemantwasthere** [comment]
Closing reason in #209 comments
