### ISSUE TITLE
[Bug]: Wrong password place holder in signup form

### ISSUE THREAD

**Issue by su-de-sh** [piyushgarg-dev/review-app#219]
### Describe the bug

The place holder in password input is '..........' instead of "Enter your password"

### To Reproduce

1. Go to 'localhost:3000'
2. Click on 'Get started for free button'
3. See error at password input

### Expected behavior

The place holder in password input is '..........' instead of "Enter your password"

### Screenshots/Videos

<img width="599" alt="Screenshot 2023-10-21 at 3 36 59 PM" src="https://github.com/piyushgarg-dev/review-app/assets/47189732/ce3ce8a2-ac85-4129-bc78-a0d12faae341">

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by su-de-sh** [comment]
@piyushgarg-dev please assign this to me

**Comment by aarjun8060** [comment]
@su-de-sh Hi, I want to work on this issue. Can you assign me ?
