### ISSUE TITLE
[Bug]: Project dropdown menu items retain background colour change even after mouse hover is removed

### ISSUE THREAD

**Issue by Amogh-Nivaskar** [piyushgarg-dev/review-app#224]
### Describe the bug

When we hover on one of the Project dropdown menu items, their background colour changes. But if we move the cursor outside of the dropdown the dropdown menu item retains its changed background colour

### To Reproduce

1. Login / Signup into the app
2. Go to dashboard
3. Open the Project dropdown menu, which is located in the navbar at the top right
4. Hover over a project name (add projects if you have none) and see that their background colour changes
5. Now, move the cursor outside of the dropdown, without it going through any other dropdown items
6. The dropdown item will retain its changed background colour even when it cursor is not hovering over it.

### Expected behavior

Imo when the cursor is not hovering over a menu item, its background colour should revert back to what it was.

## Video Demo of Bug
https://www.loom.com/share/681826d925064c37b14cacd3380dd291

## Video Demo of Proposed Solution
https://www.loom.com/share/db9aedd29a294192830cc488ce0dc6c8

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by hemantwasthere** [comment]
@Amogh-Nivaskar The proposed solution doesn't look good regarding UI/UX and ig it is good the way it is now.

If we forcefully add the hover effect on the project's background color then:
- firstly it doesn't look good and clean compared to how it is now.
- secondly, the way it is now it kind of signifies to the user that these projects are accessible or selectable using a keyboard also. 

If you can come up with a better solution then please lemme know, for now I am closing this issue and PR related to it!
Thanks for your hardworking contributions 💙🚀
