### ISSUE TITLE
[feat]: Implement Navigation from Signup Button to Dashboard 

### ISSUE THREAD

**Issue by Neel26022** [piyushgarg-dev/review-app#226]
Is your proposal related to a problem?

No

Feature Description:

click sigup button to navigate dashbord page [/dashboard]

![Screenshot (4)](https://github.com/piyushgarg-dev/review-app/assets/121471469/ad410b21-32d5-4a40-8089-b0818f34fc73)

**Comment by vs-29** [comment]
@Neel26022 I wish to resolve this issue.plz ,assign it to me.

**Comment by hemantwasthere** [comment]
@Neel26022 We're already redirecting the user to the dashboard if the user is signed in/up.

**Comment by hemantwasthere** [comment]
Closing this issue as we're already redirecting users to the dashboard

**Comment by Neel26022** [comment]
No sir not redirect error  something went to wrong
