### ISSUE TITLE
[Feat]:Placeholder Text in "Join Our Community" input in About Section of Landing Page

### ISSUE THREAD

**Issue by tanpreetjolly** [piyushgarg-dev/review-app#229]
### Is your proposal related to a problem?

There is no placeholder text inside the Input which indicated bad UX

### Describe the solution you'd like

Add a placeholder text with and adjust the font size of input so that more users can notice it and it gives a better UX to them

![image](https://github.com/piyushgarg-dev/review-app/assets/104998427/97eecc11-37cf-42c1-b053-ec74be92b542)

**Comment by tanpreetjolly** [comment]
#230

**Comment by Rishika631** [comment]
Please assign this issue to me.

**Comment by hemantwasthere** [comment]
Resolved in #230
