### ISSUE TITLE
[Bug]: Form Color in Dark Mode

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/review-app#233]
### Describe the bug

The color of Form is not correct in dark mode

### To Reproduce

Go to the Edit Form Screen and see the form

### Expected behavior

The form must be Dark in bg color

### Screenshots/Videos

<img width="1455" alt="Screenshot 2023-10-22 at 5 00 45 PM" src="https://github.com/piyushgarg-dev/review-app/assets/44976328/d83746ab-034f-4ea8-9a3e-bb8646ca0f31">

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by aarjun8060** [comment]
can you assign this to me ?

**Comment by piyushgarg-dev** [comment]
Hey @aarjun8060, Thanks for contributing. I guess you have misunderstood the Issue 😄

**Comment by aarjun8060** [comment]
@piyushgarg-dev sorry bhaiya! I am a beginner in open source. Can you tell me that I wrote the dark color in this image, we want to add dark color to this place.

<img width="944" alt="Screenshot 2023-10-12 092949" src="https://github.com/piyushgarg-dev/review-app/assets/117923579/1d13bcc8-0d24-489d-959e-4cd8c783d5f8">

**Comment by hemantwasthere** [comment]
@aarjun8060 yep, we're talking about the form's dark mode color like inputs n all.

![image](https://github.com/piyushgarg-dev/review-app/assets/85151171/a9e202f0-4739-4c1f-9ef8-1d213aa54901)

**Comment by tanpreetjolly** [comment]
#255 Hey @hemantwasthere , I added a dark mode ui. Does this looks good
![Screenshot from 2023-10-24 17-35-50](https://github.com/piyushgarg-dev/review-app/assets/104998427/194a2e26-c6c7-4f09-94cf-5418ef2ba3c6)
