### ISSUE TITLE
[Bug]: Create new form button spreads in 2 lines

### ISSUE THREAD

**Issue by Chaitanya-Shahare** [piyushgarg-dev/review-app#246]
### Describe the bug

- when the width is less the create new form button spreads to 2 lines, its not visually pleasing
- also 'Create' & 'New' imply the same thing

### To Reproduce

1. Go to `app.localhost:3000/dashboard`
2. Click on 'Forms' on the sidebar
3. Look at the `+ Create new` button
4. Decrease the width using inspect, you'll see the `Create new` button with 2 lines, this is not visually pleasing.
5. Also, 'Create' & 'New' both intend the same thing

### Expected behavior

- Use just 'Create' instead of 'Create new' it'll not split in 2 lines and will not seem like a repetition
- Makes the intended sense

### Screenshots/Videos

<img width="803" alt="Screenshot 2023-10-23 at 1 28 08 PM" src="https://github.com/piyushgarg-dev/review-app/assets/108579856/8a7804e1-21d6-4f16-bebd-e94a45bbcb32">

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by tanpreetjolly** [comment]
Please assign me this issue I will work on this
