### ISSUE TITLE
Feat: Add contributors bot

### ISSUE THREAD

**Issue by dakshsinghrathore** [piyushgarg-dev/review-app#251]
### Is your proposal related to a problem?

It would be much better if we represent the contributors in a tabular manner in [readme.md](https://github.com/piyushgarg-dev/review-app/blob/main/README.md) file which supports one click to profile feature

### Describe the solution you'd like

We can use the tool https://github.com/all-contributors/cli to achieve the task 

### Describe alternatives you've considered

NILL

### Additional context

The readme would look something like this 👇🏽

![image](https://github.com/Virtual4087/Tree2Hope/assets/115932772/be7debc2-8200-4ed4-897f-48649e139e1a)

### Requirement/Document

[(Share it here.)](https://allcontributors.org/docs/en/bot/installation)

**Comment by hemantwasthere** [comment]
Closing this issue as we already have a contributors section in our readme file
