### ISSUE TITLE
[Feat]: Improve Selected Text Color and Background Color For Better UX

### ISSUE THREAD

**Issue by Neel26022** [piyushgarg-dev/review-app#252]
### Is your proposal related to a problem?

No

Feature Description:

This feature is enhance user interface and content readability.

### Describe the solution you'd like

Background color is : #0c458 and color is : #fbf7ff

### Requirement/Document

Now:
![light1](https://github.com/piyushgarg-dev/review-app/assets/121471469/59fd783d-5d0c-4ed0-bb9f-2be721f58c1d)
![dark1](https://github.com/piyushgarg-dev/review-app/assets/121471469/f1624af1-a2f8-47fe-be62-eaa7e70f6306)

My Solution is : 
![light](https://github.com/piyushgarg-dev/review-app/assets/121471469/cbf0ecae-1f65-4597-866e-1e342270b88e)
![dark](https://github.com/piyushgarg-dev/review-app/assets/121471469/c38f3ef4-8215-48e0-9132-270eec3b158e)

**Comment by Neel26022** [comment]
Please sir check the my feature idea.
If you feel write then assign me.

**Comment by sohan9819** [comment]
@Neel26022  is this about Change Text Selection Color ?

**Comment by Neel26022** [comment]
yes

**Comment by Neel26022** [comment]
@sohan9819 yes
