### ISSUE TITLE
[Bug]: Text overlapping with Button on Landing Page in Mozilla Firefox

### ISSUE THREAD

**Issue by tanpreetjolly** [piyushgarg-dev/review-app#254]
### Describe the bug

The button is overlapping with text in the hero section of Landing Page

### To Reproduce

1. Go to Landing Page - localhost:3000 (Open on Mozilla Firefox)
2. Check the Hero Section

### Expected behavior

The button and the the text should not overlap 

### Screenshots/Videos

![image](https://github.com/piyushgarg-dev/review-app/assets/104998427/b453a20e-bb19-4dc4-b49d-d56b4ac08e25)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by tanpreetjolly** [comment]
#228

**Comment by Rishika631** [comment]
Can you assign me the issue please?

**Comment by sohan9819** [comment]
I guess these issue in occuring only on Mozilla browser , I tried to see this on chrome and brave and it was looking fine. @tanpreetjolly  did you also get this on Mozilla browser ?

**Comment by tanpreetjolly** [comment]
@sohan9819 Yeah I got it in Mozilla browser

**Comment by tanpreetjolly** [comment]
@hemantwasthere  Can you review this issue? I think this is getting unnoticed because its only happening in Mozilla Firefox and not Chromium browsers like Chrome/Brave/Edge
