### ISSUE TITLE
[Docs]: Incorrect path for env variable NEXT_PUBLIC_AWS_API_URL in CONTRIBUTING.md

### ISSUE THREAD

**Issue by cybertron15** [piyushgarg-dev/review-app#271]
### Describe the bug

path for env variable NEXT_PUBLIC_AWS_API_URL in CONTRIBUTING.md is `http://localhost:8000/local` which will not work as GraphQL backend is now being hosted on `http://localhost:8000/development`  

### To Reproduce

1. Go to CONTRIBUTING.md
2. Check Setting Up the Development Environment section

### Expected behavior

the correct value should be `http://localhost:8000/development`  

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by ArshadChowdhury** [comment]
Actually /local is working fine for me. So this might not be an issue at all and I've actually just setup the project first time today.
