### ISSUE TITLE
Create New Button in /dashboard/forms Page

### ISSUE THREAD

**Issue by ratnaraj7** [piyushgarg-dev/review-app#29]
#### Is your proposal related to a problem?

The problem is that the "Create New" button in the `/dashboard/forms` page is not disabled when no project is selected, which can lead to confusion when users proceed with creating a form without a project. And, there's no alert message to let them know about that.

https://github.com/piyushgarg-dev/review-app/assets/102022870/a15b76ab-166a-4ce3-87af-64af59616c68

#### Describe the solution you'd like

I propose that we should:

1. Disable the "Create New" button on the `/dashboard/forms` page when no project is selected.
2. Add an alert message to inform users that they need to select or create a project before proceeding.

We can use the `shadcn` alert component ([shadcn Alert Component](https://ui.shadcn.com/docs/components/alert)) to display this alert message.

#### Describe alternatives you've considered

One alternative to consider is hiding the "Forms" tab on the `/dashboard` page when no project is selected.

#### Requirement/Document
![screencapture-turbo-build-pack-docs-2023-10-07-22_08_18 (1)](https://github.com/piyushgarg-dev/review-app/assets/102022870/c20986fa-4cc6-46e1-983f-f501ebe20173)

![screencapture-app-localhost-3000-dashboard-undefined-forms-2023-10-07-22_16_18 (1)](https://github.com/piyushgarg-dev/review-app/assets/102022870/32682fdc-1c81-45cf-8f13-fd61afe6422e)

![screencapture-app-localhost-3000-dashboard-undefined-forms-2023-10-07-22_16_37 (1)](https://github.com/piyushgarg-dev/review-app/assets/102022870/4197091f-6fde-4620-8c3a-8dc6d265a3fa)

**Comment by JatinSainiOO7** [comment]
Can i work on this issue or build plz.
Thankyou...

**Comment by Himanshu-Dhawale** [comment]
Can I work on this issue?

**Comment by hemantwasthere** [comment]
Actually, we want to enforce users to create one project at least to go further, without any project users can't proceed further!
So in order to do that we'll keep the project creation modal unclosable if the user has no project.

So this is the functionality we have to implement then this issue will be solved! :)

**Comment by piyushgarg-dev** [comment]
Hey @hemantwasthere I guess it's a good idea to have this check. I agree that we will enforce the user, but adding a check won't add any extra bugs.
What do you think?

**Comment by piyushgarg-dev** [comment]
Assigning this to @ratnaraj7

**Comment by hemantwasthere** [comment]
@piyushgarg-dev yeah that would be good and more precautious.
