### ISSUE TITLE
Component Overflow Issue Causing Horizontal Scrollbar

### ISSUE THREAD

**Issue by C0dewithLokesh** [piyushgarg-dev/review-app#30]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The component is overflowing the window, leading to the appearance of a horizontal scrollbar.

### Steps to Reproduce

1. Visit the signup page by navigating to http://app.localhost:3000/dashboard.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- The component extends beyond the window's boundaries, causing a horizontal scrollbar to appear. This disrupts the user experience and layout of the page.

### Expected Results

- The component should be contained within the window's boundaries, and no horizontal scrollbar should appear. The layout and user experience should remain intact.

### Evidence

https://www.loom.com/share/78f24c6f1f1b4cb8af6a6c930f37d624?sid=23fa5bdc-0e6b-41cb-816d-303cb3b75785

![image](https://github.com/piyushgarg-dev/review-app/assets/77185999/d9596090-5c60-4390-b176-9d3091a96bc9)

**Comment by JatinSainiOO7** [comment]
can i work on this issue.
assign me plz.
thankyou...

**Comment by C0dewithLokesh** [comment]
@JatinSainiOO7  i'm already creating a pull request for this issue. Please find another issue.

**Comment by hemantwasthere** [comment]
does everyone having this issue?

**Comment by ratnaraj7** [comment]
@hemantwasthere yes

**Comment by hemantwasthere** [comment]
Okay, I'll be solving this issue!
