### ISSUE TITLE
On Cancel Form Creation Issue

### ISSUE THREAD

**Issue by ManishPJha** [piyushgarg-dev/review-app#34]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When using the "Create Form" modal, both the "Cancel" and "Continue" buttons are unintentionally creating a form. The form should only be created when the "Continue" button is clicked.

### Steps to Reproduce

1.Open the application.
2.Navigate to the "Create Form" modal.
3.Enter some data in the form fields.
4.Click the "Cancel" button.
5.Click the "Continue" button.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- When clicking the "Cancel" button, the form is being created, which is not expected behavior.

### Expected Results

- Clicking the "Cancel" button should close the modal without creating a form.
- Clicking the "Continue" button should create a form as expected.

### Evidence

[https://www.loom.com/share/871bc0945b4a4560840dec79f28ddf99](https://www.loom.com/share/871bc0945b4a4560840dec79f28ddf99)

**Comment by piyushgarg-dev** [comment]
Nice Spot 🎉
