### ISSUE TITLE
Update the README Licence

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/review-app#35]
In the README.md file, It's mentioned that we are using an MIT Licence which is incorrect. We are using the `GNU General Public License v3.0` Licence.

License File https://github.com/piyushgarg-dev/review-app/blob/main/LICENCE

Code File: https://github.com/piyushgarg-dev/review-app/blob/main/README.md?plain=1#L91-L93

**Comment by kaustab28** [comment]
I can update it. could you please assign this to me?
Thank you!
