### ISSUE TITLE
Logo svg color 

### ISSUE THREAD

**Issue by saipranay47** [piyushgarg-dev/review-app#39]
### Issue Summary
logo.svg which is inside the public folder is black because of this icons(logo) beside "remove review branding" in ```form /edit``` is not visible in dark mode

<img width="625" alt="Screenshot 2023-10-08 at 1 25 22 AM" src="https://github.com/piyushgarg-dev/review-app/assets/70259716/411963e6-61a1-4748-b88e-adb51b569c73">

### Steps to Reproduce

1. Go to dashboard ``` app.localhost:3000/dashboard```
2. switch to dark mode
3. create a project and then create a form 

### Actual Results

- currently fill in the svg is wrongly placed which is not effecting the final colour 
- <img width="1010" alt="image" src="https://github.com/piyushgarg-dev/review-app/assets/70259716/06a34b90-8637-46c8-ba79-aee18038c2da">

### Expected Results

- <img width="650" alt="image" src="https://github.com/piyushgarg-dev/review-app/assets/70259716/bea1a387-a11f-4168-bf71-46d5433080f7">

### Evidence

- I had checked the complete project for now this is the only place where this svg is used so this will not effect anything in the project

**Comment by hemantwasthere** [comment]
@saipranay47, Will you be solving this issue?
