### ISSUE TITLE
[BUG] Black colour disappear in DARK Mode   

### ISSUE THREAD

**Issue by billamitgupta** [piyushgarg-dev/review-app#45]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

This is 

### Steps to Reproduce

1. Create a form 
2. On Light Mode Black colour design are visible 
3. Turn On DARK MODE
4. Then Black colour disappears. 

If user uses dark mode then Remove Review Branding Disappears .

### Actual Results

- Dissorting website aesthetic 

### Expected Results

- Black Logos and  design should be visible visible in DARK Mode 

 
### Technical details

- Using MacBook Air M1 Laptop 
- Enable Inbuilt Dark Mode feature of Mac.

### Evidence

![Screenshot 2023-10-08 at 3 38 17 AM](https://github.com/piyushgarg-dev/review-app/assets/91731408/ab23520e-a7eb-4269-81d0-f4ef869eb03e)
-Remove review branding "LOGO" is visible 
-Powered by Review watermark present at top-right corner of form is VISIBLE

![Screenshot 2023-10-08 at 3 37 49 AM](https://github.com/piyushgarg-dev/review-app/assets/91731408/afea52f5-0e72-49ce-a072-06aa1ec0c621)
-In DARK Mode both LOGO and Watermark "disappears" 

- 

https://github.com/piyushgarg-dev/review-app/assets/91731408/21cad4ca-53df-4ac0-84ab-7e0ff86c9342

**Comment by SamakshAgarwal1112** [comment]
Can I work on this bug?

**Comment by ironsummit72** [comment]
can i work on this ?

**Comment by hemantwasthere** [comment]
This issue has been solved already! do a git pull to see the current changes.
