### ISSUE TITLE
Bug : Navbar-Logout-Issue

### ISSUE THREAD

**Issue by Hari1122-code** [piyushgarg-dev/review-app#46]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Even after the Logout the project of the previous user are still visible in the projects list.

### Steps to Reproduce

1. Login to your account
2. Create some projects and now logout from your accout
3. Even after loging out you still find your projects in the projects section in the navbar.

### Actual Results

- What's happening right now that is different from what is expected
![1](https://github.com/piyushgarg-dev/review-app/assets/77155890/93fe4c1a-d1be-4656-9223-3e2157d3982a)
![2](https://github.com/piyushgarg-dev/review-app/assets/77155890/1a04eabe-ff2c-4e34-a3d7-c4a92c721252)

### Expected Results

- This is an ideal result that the system should get after the tests are performed
- 
https://github.com/piyushgarg-dev/review-app/assets/77155890/aa87213e-7fcc-42dc-885d-35bd0aaaede4

**Comment by JOGINDER571** [comment]
Hi, I want to work on it.

**Comment by Hari1122-code** [comment]
@piyushgarg-dev  @hemantwasthere, Could you please add hacktoberfest tag to this issue
