### ISSUE TITLE
Bug: CreateProject-Logout-Issue

### ISSUE THREAD

**Issue by Hari1122-code** [piyushgarg-dev/review-app#49]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Even after logging out the Modal opens when the "Create Project" button is clicked and is available to create a new project which will not be created even if we create a new project.

### Steps to Reproduce

1. Login to your account.
2. Now log out from your account and try to create a new project.
3. the modal will be opened to create a new project

### Actual Results

https://github.com/piyushgarg-dev/review-app/assets/77155890/6d6fc53e-d9ab-49b3-b285-c16a58e500d8

### Expected Results

https://github.com/piyushgarg-dev/review-app/assets/77155890/23e105af-326c-4666-b19e-84534fc7c80a

**Comment by Hari1122-code** [comment]
@piyushgarg-dev  @hemantwasthere, Could you please add hacktoberfest tag to this issue

**Comment by hemantwasthere** [comment]
Hey @Hari1122-code, Actually the ideal case would be that if you user is logged out then he or she should not be able to access dashboard without logging in.

**Comment by Hari1122-code** [comment]
> Hey @Hari1122-code, Actually the ideal case would be that if you user is logged out then he or she should not be able to access dashboard without logging in.

Ohh kk @hemantwasthere that makes sense, 
Now can I make another PR to resolve the issue by redirecting to signin page

**Comment by hemantwasthere** [comment]
@Hari1122-code Okay when your PR is ready create a new issue and a new PR linked with your issue.
I am closing this issue and PR for now!

**Comment by Hari1122-code** [comment]
> @Hari1122-code Okay when your PR is ready create a new issue and a new PR linked with your issue. I am closing this issue and PR for now!

Sorry for the late reply @hemantwasthere 
Actually i am trying to protect the routes by checking the auth in the middleware.ts file in which I am not successful as the Authorization token is stored in the localstorage and cannot be accessed in the server-side.
meanwhile someone has created this issue and resolved it in the frontend in the issue #102
