### ISSUE TITLE
Create `CONTIBUTING.md`

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/review-app#5]
Can you create a CONTIBUTING.md file with all the detailed instructions on how to contribute and set up this project locally? This would help them contribute to setting up and running the project on localhost.

**Comment by priyankeshh** [comment]
Please assign this issue to me. Thank you!

**Comment by parthksingh1** [comment]
Please assign me this issue

**Comment by sum1t-here** [comment]
Please assign me this

**Comment by piyushgarg-dev** [comment]
Hey @parthksingh1 Can you take this task, please? https://github.com/piyushgarg-dev/review-app-api/issues/3
Please add your comment there so that I can assign that to you.

**Comment by Vivek7038** [comment]
which things you want to be covered in CONTIBUTING.md .

- [ ] local setup of project 
- [ ] conventions for pull requests 
- [ ] branching conventions 
- [ ] which logo which I should use 
-

**Comment by anshul-132002** [comment]
Hey! @piyushgarg-dev i want to contribute to this issue

**Comment by rahul429-wq** [comment]
> Can you create a CONTIBUTING.md file with all the detailed instructions on how to contribute and set up this project locally? This would help them contribute to setting up and running the project on localhost.

assign me sir

**Comment by KunjMaheshwari** [comment]
Hey! @piyushgarg-dev Please assign this issue to me. I am new to open source and would love to contribute for you.
