### ISSUE TITLE
Remove the support for slug in backend

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/review-app#57]
Ref Issue https://github.com/piyushgarg-dev/review-app/issues/56

**Comment by hemantwasthere** [comment]
@piyushgarg-dev this issue solved right? we can close it now!

**Comment by piyushgarg-dev** [comment]
Yes

**Comment by piyushgarg-dev** [comment]
Closing this in Ref to https://github.com/piyushgarg-dev/review-app/commit/2230905e5d0ca972509ce7d0c98fe4619c827506
