### ISSUE TITLE
[Bug] Text truncate is not working for Display Name on Top Header

### ISSUE THREAD

**Issue by yshashi** [piyushgarg-dev/review-app#58]
### Issue Summary

Once the user logged if the display name is more than 14 characters it adds a scrollbar bar at the bottom of the sidebar

### Steps to Reproduce

1. Login to the application
2. Make sure to have the FirstName + LastName be more than 14 characters
3. Observe at top and bottom of the sidebar

### Actual Results

- There are no ellipses and scrollbar at the bottom of the sidebar
![image](https://github.com/piyushgarg-dev/review-app/assets/21971232/12638244-7351-4cc5-b275-03bd3461f47f)

https://github.com/piyushgarg-dev/review-app/assets/21971232/97eea730-e165-4e59-971a-c12652b4b37b

### Expected Results

- There should be ellipses and no scrollbar at the bottom as per applied truncate class
![image](https://github.com/piyushgarg-dev/review-app/assets/21971232/80cf2454-5d3f-4ac3-afd9-6aded8221e79)

https://github.com/piyushgarg-dev/review-app/assets/21971232/4a9be5d8-0305-4f06-84d0-3e35dd218dc6

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

**Comment by C0dewithLokesh** [comment]
This issue has already been resolved. Please make sure to sync your fork and verify it.
PR #51

**Comment by yshashi** [comment]
As the issue is already been resolved with PR #51 
So closing the issue
