### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/review-app#6]
Add a README file in this project to explain what this project is about and various more details about this project to help understand what this project does.

**Comment by priyankeshh** [comment]
Hi there,

I'd like to contribute to this project. Could you assign this issue to me. Also could you provide the following information? It would greatly assist me in making a more comprehensive README file

-Logo. If you have a logo for the project, please share it.
-Could you provide a list of key features that the Review App offers? This will help us highlight what makes this project unique and valuable.

**Comment by parthksingh1** [comment]
Please assign me this issue

**Comment by sum1t-here** [comment]
Please assign me this

**Comment by dCOMMICS** [comment]
please assign me

**Comment by hemantwasthere** [comment]
@priyankeshh checkout [this](https://www.youtube.com/watch?v=JD3NQsB3TQI) and see what the project is about and how its working!

**Comment by anshul-132002** [comment]
Hey! @piyushgarg-dev i want to contribute to this issue

**Comment by KunjMaheshwari** [comment]
Please @piyushgarg-dev Assign this issue to me. I am new to open source, and saw your video on YouTube about Hacktoberfest - subscribed you for more updates. Please let me do this.

**Comment by KunjMaheshwari** [comment]
Hey! @piyushgarg-dev I made one README.md for you 

# Next.js Project Accelerated Launch Guide

Supercharge your Next.js project with this cutting-edge template bootstrapped using `create-next-app`.

## Dive into Action

1. **Ignite the Development Server**

   Launch the development server with your preferred package manager:

   ```bash
   npm run dev
   # or
   yarn dev
   # or
   pnpm dev
   ```

   Witness your project come to life by opening [http://localhost:3000](http://localhost:3000) in your browser.

2. **Craft Your Digital Masterpiece**

   Embark on your creative journey by personalizing the default page. Empower your ideas by crafting changes in `pages/index.tsx`. Marvel at how your page evolves in real-time as you sculpt it.

3. **Unleash API Wizardry**

   Command API routes with the flair of a wizard! Explore the mystical realms of API endpoints at [http://localhost:3000/api/hello](http://localhost:3000/api/hello). Mold this magical endpoint into your own creation by weaving your spells within the `pages/api/hello.ts` file. Remember, the `pages/api` directory is your cauldron for brewing API routes, not just React pages.

4. **Font Alchemy**

   This project employs the powerful `next/font` sorcery to automatically optimize and conjure the Inter font, a bespoke Google Font experience.

## Deepen Your Knowledge

To become a true Next.js sorcerer, delve into these arcane tomes:

- [Next.js Documentation](https://nextjs.org/docs) - Uncover the hidden secrets of Next.js, its mystical features, and powerful API incantations.
- [Learn Next.js](https://nextjs.org/learn) - Immerse yourself in the interactive Next.js tutorial, where you'll gain hands-on mastery.
- [Next.js GitHub Repository](https://github.com/vercel/next.js) - Join the fellowship of contributors in shaping the future of Next.js, where your insights and enhancements are most welcome!

## Ascend to the Clouds

For the ultimate ascension of your Next.js creation, cast it onto the cloud with the celestial Vercel Platform. Your project will soar to new heights, and you'll find guidance in our mystical [Next.js deployment documentation](https://nextjs.org/docs/deployment).

Join the ranks of those who have harnessed the power of Next.js, and together, let's weave a tale of web development wizardry!

**Comment by piyushgarg-dev** [comment]
Hey @KunjMaheshwari please raise a PR 😄

**Comment by piyushgarg-dev** [comment]
Closing this in ref https://github.com/piyushgarg-dev/review-app/pull/8
Please add fixes <ISSUE_NUMBER>
