### ISSUE TITLE
[Bug]: Padding issue in the container of form name

### ISSUE THREAD

**Issue by Sharathchandra345** [piyushgarg-dev/review-app#60]
### Describe the bug

Issue with the container of the form name 

### To Reproduce

1. Go to Dashboard
2. Click on Forms
3. Create a form
4. See error on top left

![image](https://github.com/piyushgarg-dev/review-app/assets/118743483/fcd43fe9-446f-4e94-bc91-8f6ce3b0a145)

### Expected behavior

Whole name of the form should be visible 

### Screenshots/Videos

![image](https://github.com/piyushgarg-dev/review-app/assets/118743483/25ec0d04-96f9-48b6-ac13-e207b4d2d83e)

### Additional context

Paddinng of container to be fixed

### Please checkmark the following checklist

- [x] I make sure that similar issue is not opened

**Comment by MeethDavda** [comment]
I can work on it.

**Comment by hemantwasthere** [comment]
Closing reason explained in PR #65
