### ISSUE TITLE
[Bug]: Dark theme is not working properly for forms preview while creating new form

### ISSUE THREAD

**Issue by AmitSaha15** [piyushgarg-dev/review-app#68]
### Describe the bug

When dark theme is applied the text "Powered by Review" and the heart shaped logos are not visible.

### To Reproduce

While dark theme is applied
1. Go to 'dashboard'
2. Click on 'Forms'
3. Then click on 'Create new'

### Expected behavior

The logos and text should be visible.

### Screenshots/Videos

https://github.com/piyushgarg-dev/review-app/assets/95316932/d839b755-00c6-4ad0-9972-9844b04b4c21

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by sushilmagare10** [comment]
Working on it **@AmitSaha15**

**Comment by AmitSaha15** [comment]
Yeah just saw there is already an issue regarding this. Closing the issue.


> Working on it **@AmitSaha15**
