### ISSUE TITLE
Landing Pages for Review App for SEO V2

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/review-app#7]
### Create a SEO Friendly landing page for the Review app at `/landing`

As of now, This project has no landing pages or home pages. As you have already got an idea of what exactly this app does. It would be great if you could build a SEO friendly modern landing page with animations.

Here are some inspirations and Ideas
1. https://senja.io/
2. https://www.landingfolio.com/templates/post/saasfolio

> P.S - These links are only for inspiration, Please do not copy them exactly 😄

**Comment by HarshMN2345** [comment]
please assign this issue to me

**Comment by MeethDavda** [comment]
I would like to work on it. Please assign it to me. Thanks

**Comment by Zaheer-zk** [comment]
I'm interested in developing the SEO-friendly landing page as described in Issue #4  and have some great ideas inspired by the provided links. Could you please assign this issue to me? I'm excited to contribute and ready to get started!

**Comment by piyushgarg-dev** [comment]
Hey @Zaheer-zk @aditya-mistri 
I assigned this issue to @MeethDavda but you can take this one https://github.com/piyushgarg-dev/review-app/issues/11 😄

**Comment by Zaheer-zk** [comment]
> Hey @Zaheer-zk @aditya-mistri I assigned this issue to @MeethDavda but you can take this one #11 😄

Already assigned to Aditya

**Comment by piyushgarg-dev** [comment]
Dont

> > Hey @Zaheer-zk @aditya-mistri I assigned this issue to @MeethDavda but you can take this one #11 😄
> 
> Already assigned to Aditya

Don't worry @Zaheer-zk 
You can take this up, We eventually need multiple Landing Pages :)

**Comment by piyushgarg-dev** [comment]
Hi @Zaheer-zk,
Can you ping me on discord, I'll assign you a Landing page task 😄
