### ISSUE TITLE
Create a Proxy Signin and Signup Page

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/review-app#70]
As we have the original Signin and Signup page on a custom domain that is `app.localhost:3000/signin`, we require to create a `/signin` and `/signup` page on the root domain as well so that if anyone visits `localhost:3000/signin` this redirects to `app.localhost:3000/signin` and same for signup page as well.

Note: Please use the domain name from process.env to redirect the user.

**Comment by Hari1122-code** [comment]
Hey, Can you please assign this issue to me.

**Comment by piyushgarg-dev** [comment]
Assigned to @Hari1122-code

**Comment by Hari1122-code** [comment]
Thank You for assigning.

I have a small doubt
Should i create a /signin and /signup page on the root domain so that if anyone visits localhost:3000/signin this redirects to app.localhost:3000/signin or Can i handle this directly from the middleware.ts file.

**Comment by shyamraghu** [comment]
@piyushgarg-dev can i work on this issue

**Comment by piyushgarg-dev** [comment]
@Hari1122-code You can take a call on it 😄
