### ISSUE TITLE
[Bug]: Add validation on subdomain while creating Project

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/review-app#72]
### Describe the bug

There is no validation on the subdomain while creating a subdomain in the project section. We have to make sure that the subdomain is a plan text without spaces and special char

### To Reproduce

1. Signin to `app.localhost:3000/signin`
2. Go to Dashboard `app.localhost:3000/dashboard`
3. Create a new Project
4. Add subdomain as hey there
5. The project creates but there should be a validation on correct subdomain

### Expected behavior

Need something similar to this in design
<img width="420" alt="Screenshot 2023-10-08 at 3 02 40 PM" src="https://github.com/piyushgarg-dev/review-app/assets/44976328/56fb44c1-894e-46b3-a2d5-4e4d4ba9b8f0">

### Screenshots/Videos

<img width="532" alt="Screenshot 2023-10-08 at 3 00 49 PM" src="https://github.com/piyushgarg-dev/review-app/assets/44976328/213a292f-d105-42b1-9917-cf4724534a7b">

### Additional context

Use the following regex to validate the input:
```js
const regex = /^[a-z0-9]+$/;
```

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by harshsharma-11** [comment]
please assign this to me.i am working on this
