### ISSUE TITLE
Create First Project Button

### ISSUE THREAD

**Issue by rahulsan007** [piyushgarg-dev/review-app#74]
### Description

I'm proposing the addition of a "Create First Project" button to the dashboard page instead of "Dashboard Page" text for new users. This button will serve as a quick and intuitive way for users to initiate the process of creating their first project.

### Proposed Changes

- Add a button with the label "Create First Project" ].
- Implement functionality to trigger the project creation process.

**Comment by ShreyasSaunshi** [comment]
Hy, can you please assign me this?

**Comment by hemantwasthere** [comment]
Closing reason in #75
