### ISSUE TITLE
[Bug]:Can't SignUp. It says Something went wrong while signup

### ISSUE THREAD

**Issue by shreyash-0928** [piyushgarg-dev/review-app#85]
### Describe the bug

Fix Login/SignUp issues so that I can signin to contribute

### To Reproduce

1. Go to http://app.localhost:3000/signup
2. Fill all the details
3. Click SignUp
4. See error - Something went wrong(can't signUp)

### Expected behavior

Successfully signUp operation should work properly 

### Screenshots/Videos

![Screenshot 2023-10-08 180626](https://github.com/piyushgarg-dev/review-app/assets/115428875/e3d2770a-c383-4316-aa5f-00b8070e11d7)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by SammitBadodekar** [comment]
have you setup backend ?

**Comment by SammitBadodekar** [comment]
yep, facing same issue

**Comment by saadabban76** [comment]
facing same ! don't know what's the issue tho

**Comment by CodeAnk2829** [comment]
Hey @shreyash-0928, I would like to work on this issue. Please assign me.

**Comment by piyushgarg-dev** [comment]
https://discord.com/channels/1082554321306136696/1160191631203516477/1160584070514876547

**Comment by CodeAnk2829** [comment]
> Please Read This https://discord.com/channels/1082554321306136696/1160191631203516477/1160490505172434944

I guess this issue is no longer valid, right?

**Comment by shreyash-0928** [comment]
> Hey @shreyash-0928, I would like to work on this issue. Please assign me.
I think i don't have access to assign issue.

**Comment by ChaudharyPradip** [comment]
Hey everyone,
I also faced this issue but it's not actually an issue related to the project. The thing is that frontend & backend are on different URLs and so if you have an ad blocker or something it blocks the request to the other URLs. So you just need to disable it for the review app and it will work fine.

**Comment by shreyash-0928** [comment]
> Hey everyone,
> I also faced this issue but it's not actually an issue related to the project. The thing is that frontend & backend are on different URLs and so if you have an ad blocker or something it blocks the request to the other URLs. So you just need to disable it for the review app and it will work fine.

Okay I will try.... Thankyou

**Comment by shreyash-0928** [comment]
> Hey everyone, I also faced this issue but it's not actually an issue related to the project. The thing is that frontend & backend are on different URLs and so if you have an ad blocker or something it blocks the request to the other URLs. So you just need to disable it for the review app and it will work fine.

Bro didnt work whem ad blocker disabled, Its still the same
