### ISSUE TITLE
Mandatory Project Creation for Dashboard Access

### ISSUE THREAD

**Issue by hemantwasthere** [piyushgarg-dev/review-app#91]
### Hey everyone 👋 

 I've noticed that many of you are raising issues and PR's regarding actions to be taken when no project is selected.

However, I would like to outline the approach we will be following:
- We will require users to create a project if they do not already have one. This enforcement is necessary to enable them to view their project on the dashboard.

- Additionally, I encourage you to raise pull requests aimed at resolving this enforcement functionality for the user.

- Therefore, I kindly request that you keep this in mind when creating new issues or pull requests related to this topic.

Please let me know if there's anything else I can assist you with and Keep contributing 😊💙

**Comment by piyushgarg-dev** [comment]
@hemantwasthere I am assigning this to you. Can you take this and complete it up?

**Comment by ruhani2** [comment]
Hello @hemantwasthere ,

As per the description, when the form is created project reinforcement is required.
Following are the two approaches I would like to propose,

1. After login when the user clicks on forms in the left sidebar, it changes the URL to [URL]/dashboard/**undefined**/forms when the project is not created. Which is not good from a UX perspective. Maybe we should first show a popup saying please select a project, or If none exists, please create a project. After the user creates or selects a project, they should be redirected to their project's forms page.

2. The second approach can be rather than having forms on the sidebar, as forms totally dependent on project creation, should show projects instead of forms on the sidebar? user can navigate to a particular project and see respective forms ?

Let me know if the above approaches look fine ?
Please let me know your thoughts and suggestions.

cc. @piyushgarg-dev

**Comment by hemantwasthere** [comment]
> Hello @hemantwasthere ,
> 
> As per the description, when the form is created project reinforcement is required. Following are the two approaches I would like to propose,
> 
>     1. After login when the user clicks on forms in the left sidebar, it changes the URL to [URL]/dashboard/**undefined**/forms when the project is not created. Which is not good from a UX perspective. Maybe we should first show a popup saying please select a project, or If none exists, please create a project. After the user creates or selects a project, they should be redirected to their project's forms page.
> 
>     2. The second approach can be rather than having forms on the sidebar, as forms totally dependent on project creation, should show projects instead of forms on the sidebar? user can navigate to a particular project and see respective forms ?
> 
> 
> Let me know if the above approaches look fine ? Please let me know your thoughts and suggestions.
> 
> cc. @piyushgarg-dev

I think you got it wrong, as per the description when user is logged in or signed up for the first time then he/she should be enforced to create a project in order to move further else without creating a project, dashboard won't be accessible.

cc: @piyushgarg-dev

**Comment by ruhani2** [comment]
> > Hello @hemantwasthere ,
> > As per the description, when the form is created project reinforcement is required. Following are the two approaches I would like to propose,
> > ```
> > 1. After login when the user clicks on forms in the left sidebar, it changes the URL to [URL]/dashboard/**undefined**/forms when the project is not created. Which is not good from a UX perspective. Maybe we should first show a popup saying please select a project, or If none exists, please create a project. After the user creates or selects a project, they should be redirected to their project's forms page.
> > 
> > 2. The second approach can be rather than having forms on the sidebar, as forms totally dependent on project creation, should show projects instead of forms on the sidebar? user can navigate to a particular project and see respective forms ?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know if the above approaches look fine ? Please let me know your thoughts and suggestions.
> > cc. @piyushgarg-dev
> 
> I think you got it wrong, as per the description when user is logged in or signed up for the first time then he/she should be enforced to create a project in order to move further else without creating a project, dashboard won't be accessible.
> 
> cc: @piyushgarg-dev

okay, I think it is similar to my first approach where the user can not access the forms page without creating the project, as for forms project is required/mandatory. 

In your approach, it is restricting users from accessing the dashboard. This one is also nice.

But there are other pages as well that he/she wanna visit(ex - maybe in the future if roles get introduced), is it fine to restrict dashboard access?

Just wondering if all users will come only to create review forms.

**Comment by ruhani2** [comment]
Hello @hemantwasthere I would love to work on this. Please assign this to me if this issue is still valid.

**Comment by hemantwasthere** [comment]
> Hello @hemantwasthere I would love to work on this. Please assign this to me if this issue is still valid.

sure
