### ISSUE TITLE
[Bug]: Input text in DarkMode

### ISSUE THREAD

**Issue by sushilmagare10** [piyushgarg-dev/review-app#94]
### Describe the bug

The inupt text is not visible in the DarkMode

### To Reproduce

1. Go to 'forms using darkmode'
2. Click on 'Customers Details'

### Expected behavior

The input Text should have White color in the darkmode

### Screenshots/Videos

![input-err-in-darkmode](https://github.com/piyushgarg-dev/review-app/assets/115215071/1114fe50-3190-40b3-a68c-ce9352fad4c2)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by Bansalayush247** [comment]
Is this issue still available
