### ISSUE TITLE
docs : Add contributors section in readme.md file and website demo gif

### ISSUE THREAD

**Issue by YashkShrivas4491** [piyushgarg-dev/review-app#95]
### Is your proposal related to a problem?

   1. I want to add the contributor's section in the Readme.md file 
   2. Add the Website(Review App) demo GIF
### Describe the solution you'd like

<a href="https://github.com/piyushgarg-dev/review-app/contributors">
 <img src="https://contrib.rocks/image?repo=piyushgarg-dev/review-app" />
</a>

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

**Comment by devmusiczz** [comment]
duplicate issue #23

**Comment by YashkShrivas4491** [comment]
> duplicate issue #23

Ok removing it
